### ISSUE TITLE
Add support for label formatter

### ISSUE THREAD

**Issue by hdoria** [philackm/Scrollable-GraphView#18]
Is there a way to format the label on y axis? Would be great to be able to format the string. It's useful to display currency and other types of data.

**Comment by philackm** [comment]
The only options at the moment for the labels on the y-axis are:

| Property | Description |
|----------|-------------|
|**referenceLineLabelFont**|The font to be used for the reference line labels.|
|**referenceLineLabelColor**|The colour of the reference line labels.|
|**shouldShowReferenceLineUnits**|Whether or not to show the units on the reference lines.|
|**referenceLineUnits**|The units that the y-axis is in. This string is used for labels on the reference lines.|
|**referenceLineNumberOfDecimalPlaces**|The number of decimal places that should be shown on the reference line labels.|

So for example, if you wanted the labels on the y-axis to look something like:

2.0 metres
1.5 metres
1.0 metres

You could use:

```
graphView.shouldShowReferenceLineUnits = true
graphView.referenceLineUnits = "metres"
graphView.referenceLineNumberOfDecimalPlaces = 1
```

I think I might change this in the future so that you can provide a closure to customise the label however you want, but for now the above is all that is possible.

**Comment by timbroder** [comment]
I made this #30  before I saw this ticket
@hdoria would using a NSNumberFormatterStyle do what you need?

**Comment by philackm** [comment]
I think pull request #30 satisfies this. If not feel free to re-open it!
